import { NextRequest, NextResponse } from 'next/server';
import fs from 'fs/promises';
import path from 'path';

/**
 * GET /api/install-windows?token=...&url=...&workspaceId=...
 *
 * Dynamically generates a PowerShell install script for the Glanus Agent.
 * Downloads the .msi, installs silently, and registers with the server.
 */
export async function GET(request: NextRequest) {
    const { searchParams } = request.nextUrl;
    const token = searchParams.get('token');
    const workspaceId = searchParams.get('workspaceId');

    if (!token || !workspaceId) {
        return new NextResponse('Write-Error "Missing required parameters (token, workspaceId)"; exit 1', {
            status: 400,
            headers: { 'Content-Type': 'text/plain; charset=utf-8' },
        });
    }

    // Derive origin from the actual incoming request — see install-linux
    // route for the rationale (avoids port mismatches and SSRF surface).
    const xfHost = request.headers.get('x-forwarded-host');
    const xfProto = request.headers.get('x-forwarded-proto');
    const host = xfHost || request.headers.get('host') || request.nextUrl.host;
    const proto = xfProto || request.nextUrl.protocol.replace(':', '') || 'http';
    const origin = `${proto}://${host}`;
    const apiUrl = origin;

    const canonicalMsiPath = path.join(process.cwd(), 'glanus-agent', 'builds', 'windows', 'glanus-agent.msi');
    try {
        await fs.stat(canonicalMsiPath);
    } catch {
        return new NextResponse(
            'Write-Error "Windows installer is not available on this server. Expected glanus-agent/builds/windows/glanus-agent.msi. Linux agent artifacts are unchanged."; exit 1',
            {
                status: 200,
                headers: { 'Content-Type': 'text/plain; charset=utf-8' },
            }
        );
    }

    const msiUrl = `${origin}/api/downloads/glanus-agent.msi`;

    const script = `# Glanus Agent - Automated Windows Installer
# Generated dynamically by the Glanus server
# Run in an Administrator PowerShell session

\$ErrorActionPreference = "Stop"
\$AgentMSI = "\$env:TEMP\\GlanusAgent.msi"
\$ApiUrl = "${apiUrl}"
\$Token = "${token}"

Write-Host "============================================" -ForegroundColor Cyan
Write-Host "  Glanus Agent - Windows Installer" -ForegroundColor Cyan
Write-Host "============================================" -ForegroundColor Cyan
Write-Host ""

# Check for admin privileges
if (-NOT ([Security.Principal.WindowsPrincipal] [Security.Principal.WindowsIdentity]::GetCurrent()).IsInRole([Security.Principal.WindowsBuiltInRole]::Administrator)) {
    Write-Error "This script must be run as Administrator."
    exit 1
}

Write-Host "[1/4] Downloading Glanus Agent..." -ForegroundColor Yellow
try {
    [Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12
    Invoke-WebRequest -Uri "${msiUrl}" -OutFile \$AgentMSI -UseBasicParsing
} catch {
    Write-Error "Download failed: \$_"
    exit 1
}

Write-Host "[2/4] Installing agent..." -ForegroundColor Yellow
\$installArgs = "/i \$AgentMSI PRE_AUTH_TOKEN=\$Token API_ENDPOINT=\$ApiUrl WORKSPACE_ID=${workspaceId} /quiet /norestart"
\$process = Start-Process -FilePath "msiexec.exe" -ArgumentList \$installArgs -Wait -PassThru
if (\$process.ExitCode -ne 0) {
    Write-Error "Installation failed with exit code: \$(\$process.ExitCode)"
    exit 1
}

Write-Host "[3/4] Writing agent config..." -ForegroundColor Yellow
\$configDir = "\$env:ProgramData\\Glanus"
New-Item -ItemType Directory -Force -Path \$configDir | Out-Null
\$ConfigFile = "\$configDir\\config.toml"

@"
# Glanus Agent configuration (auto-generated by install script)
# Do not edit while the service is running.

[agent]
version = "0.1.0"
workspace_id = "${workspaceId}"
pre_auth_token = "\$Token"
registered = \$false

[server]
api_url = "\$ApiUrl"
heartbeat_interval = 60

[monitoring]
enabled = \$true
interval = 10
include_processes = \$true
max_processes = 5

[updates]
enabled = \$true
check_interval = 86400
auto_install = \$false

[inventory]
enabled = \$true
sync_interval = 21600

[discovery]
enabled = \$false
scan_interval = 3600

[remote]
enabled = \$true
"@ | Out-File -FilePath \$ConfigFile -Encoding UTF8

Write-Host "[4/4] Starting service..." -ForegroundColor Yellow
try {
    Start-Service -Name "GlanusAgent" -ErrorAction SilentlyContinue
} catch {
    Write-Host "[INFO] Service will start on next system boot." -ForegroundColor DarkYellow
}

# Cleanup
Remove-Item -Force \$AgentMSI -ErrorAction SilentlyContinue

Write-Host ""
Write-Host "============================================" -ForegroundColor Green
Write-Host "  Glanus Agent installed successfully!" -ForegroundColor Green
Write-Host "  Service: Get-Service GlanusAgent" -ForegroundColor Green
Write-Host "============================================" -ForegroundColor Green
`;

    return new NextResponse(script, {
        status: 200,
        headers: {
            'Content-Type': 'text/plain; charset=utf-8',
            'Content-Disposition': 'inline; filename="install-glanus.ps1"',
            'Cache-Control': 'no-store',
        },
    });
}
