import { apiSuccess, apiError } from '@/lib/api/response';
import { NextRequest } from 'next/server';
import { withErrorHandler } from '@/lib/api/withAuth';
import { z } from 'zod';
import { withRateLimit } from '@/lib/security/rateLimit';
import { consumePreAuthToken } from '@/lib/security/preauth-store';
import { AgentService } from '@/lib/services/AgentService';
import { AgentPlatform } from '@prisma/client';
import crypto from 'crypto';

const registerSchema = z.object({
    assetId: z.string().optional(),
    workspaceId: z.string(),
    hostname: z.string(),
    platform: z.enum(['WINDOWS', 'MACOS', 'LINUX']),
    ipAddress: z.string().optional(),
    macAddress: z.string().optional(),
    agentVersion: z.string(),
    systemInfo: z.object({
        cpu: z.string(),
        ram: z.number(),
        disk: z.number(),
        os: z.string(),
    }).optional(),
});

/**
 * Agent registration endpoint.
 *
 * Authentication model: The agent sends a pre-auth token (generated by a
 * logged-in workspace admin via the download-agent endpoint) as a Bearer
 * header. We do NOT require a NextAuth session here because agents are
 * headless desktop processes without browser cookies.
 *
 * Security: Only workspace admins can generate pre-auth tokens (that flow
 * requires requireAuth + requireWorkspaceAccess). AgentService.registerAgent
 * validates that the workspace and asset exist and are linked.
 */
export const POST = withErrorHandler(async (request: NextRequest) => {
    // Require a Bearer token (pre-auth token from download-agent flow)
    const authHeader = request.headers.get('Authorization');
    if (!authHeader?.startsWith('Bearer ')) {
        return apiError(401, 'Missing or invalid Authorization header');
    }
    const preAuthToken = authHeader.substring(7);

    const preAuthRateKey = crypto.createHash('sha256').update(preAuthToken).digest('hex');
    const rateLimitResponse = await withRateLimit(request, 'agent', `agent-register:${preAuthRateKey}`);
    if (rateLimitResponse) return rateLimitResponse;

    const data = registerSchema.parse(await request.json());

    // Validate the pre-auth token was issued for this workspace
    if (!(await consumePreAuthToken(preAuthToken, data.workspaceId))) {
        return apiError(401, 'Invalid or expired pre-auth token');
    }

    // AgentService validates workspace existence and asset-workspace relationship
    const result = await AgentService.registerAgent({
        ...data,
        platform: data.platform as AgentPlatform,
    });
    return apiSuccess(result);
});
