import crypto from 'crypto';
import { prisma } from '@/lib/db';

/**
 * Pre-Auth Token Store — Manages short-lived tokens for agent registration.
 *
 * Tokens are generated by workspace admins (download-agent flow) and consumed
 * once during agent registration. Stored in-memory with TTL expiration.
 *
 * Security properties:
 *  - Tokens are stored as HMAC-SHA256 hashes (never plaintext)
 *  - Single-use: consumed on successful validation
 *  - TTL-based expiration (default 7 days, matching download-agent flow)
 *  - Scoped to a specific workspaceId
 */

const TOKEN_SECRET = process.env.PREAUTH_TOKEN_SECRET || process.env.CSRF_SECRET || 'dev-only-preauth-secret';
const DEFAULT_TTL_MS = 7 * 24 * 60 * 60 * 1000; // 7 days

if (process.env.NODE_ENV === 'production' && TOKEN_SECRET === 'dev-only-preauth-secret') {
    throw new Error('PREAUTH_TOKEN_SECRET or CSRF_SECRET must be configured in production');
}

function hashToken(token: string): string {
    return crypto.createHmac('sha256', TOKEN_SECRET).update(token).digest('hex');
}

/**
 * Store a pre-auth token for later validation during agent registration.
 */
export async function storePreAuthToken(
    token: string,
    workspaceId: string,
    issuedById: string,
    ttlMs: number = DEFAULT_TTL_MS
): Promise<void> {
    const tokenHash = hashToken(token);
    await prisma.agentPreAuthToken.create({
        data: {
            tokenHash,
            workspaceId,
            issuedById,
            expiresAt: new Date(Date.now() + ttlMs),
        },
    });
}

/**
 * Validate and consume a pre-auth token.
 * Returns true only when a non-expired token is atomically consumed.
 * Token is consumed (deleted) on successful validation.
 */
export async function consumePreAuthToken(token: string, workspaceId: string): Promise<boolean> {
    const tokenHash = hashToken(token);
    const now = new Date();

    const result = await prisma.agentPreAuthToken.updateMany({
        where: {
            tokenHash,
            workspaceId,
            consumedAt: null,
            expiresAt: { gt: now },
        },
        data: {
            consumedAt: now,
        },
    });

    return result.count === 1;
}

/**
 * Best-effort cleanup for consumed/expired pre-auth tokens.
 */
export async function purgePreAuthTokens(): Promise<number> {
    const result = await prisma.agentPreAuthToken.deleteMany({
        where: {
            OR: [
                { consumedAt: { not: null } },
                { expiresAt: { lt: new Date() } },
            ],
        },
    });
    return result.count;
}
