import crypto from 'crypto';

/**
 * Pre-Auth Token Store — Manages short-lived tokens for agent registration.
 *
 * Tokens are generated by workspace admins (download-agent flow) and consumed
 * once during agent registration. Stored in-memory with TTL expiration.
 *
 * Security properties:
 *  - Tokens are stored as HMAC-SHA256 hashes (never plaintext)
 *  - Single-use: consumed on successful validation
 *  - TTL-based expiration (default 7 days, matching download-agent flow)
 *  - Scoped to a specific workspaceId
 */

const TOKEN_SECRET = process.env.PREAUTH_TOKEN_SECRET || process.env.CSRF_SECRET || 'dev-only-preauth-secret';
const DEFAULT_TTL_MS = 7 * 24 * 60 * 60 * 1000; // 7 days

interface StoredToken {
    hash: string;
    workspaceId: string;
    expiresAt: number;
}

// In-memory store with periodic cleanup
const tokenStore = new Map<string, StoredToken>();

function hashToken(token: string): string {
    return crypto.createHmac('sha256', TOKEN_SECRET).update(token).digest('hex');
}

/**
 * Store a pre-auth token for later validation during agent registration.
 */
export function storePreAuthToken(token: string, workspaceId: string, ttlMs: number = DEFAULT_TTL_MS): void {
    const hash = hashToken(token);
    tokenStore.set(hash, {
        hash,
        workspaceId,
        expiresAt: Date.now() + ttlMs,
    });

    // Lazy cleanup: remove expired tokens when store grows
    if (tokenStore.size > 100) {
        const now = Date.now();
        for (const [key, entry] of tokenStore) {
            if (entry.expiresAt < now) tokenStore.delete(key);
        }
    }
}

/**
 * Validate and consume a pre-auth token.
 * Returns the workspaceId if valid, null otherwise.
 * Token is consumed (deleted) on successful validation.
 */
export function consumePreAuthToken(token: string, workspaceId: string): boolean {
    const hash = hashToken(token);
    const entry = tokenStore.get(hash);

    if (!entry) return false;
    if (entry.expiresAt < Date.now()) {
        tokenStore.delete(hash);
        return false;
    }
    if (entry.workspaceId !== workspaceId) return false;

    // Single-use: consume the token
    tokenStore.delete(hash);
    return true;
}
