import { NextRequest, NextResponse } from 'next/server';

/**
 * GET /api/install-macos?token=...&url=...&workspaceId=...
 *
 * Dynamically generates a bash install script for the Glanus Agent on macOS.
 * Downloads the .pkg, installs it, and registers with the server.
 */
export async function GET(request: NextRequest) {
    const { searchParams } = request.nextUrl;
    const token = searchParams.get('token');
    const workspaceId = searchParams.get('workspaceId');

    if (!token || !workspaceId) {
        return new NextResponse('#!/bin/bash\necho "Error: Missing required parameters (token, workspaceId)"\nexit 1\n', {
            status: 400,
            headers: { 'Content-Type': 'text/plain; charset=utf-8' },
        });
    }

    // Derive origin from the actual incoming request — see install-linux
    // route for the rationale (avoids port mismatches and SSRF surface).
    const xfHost = request.headers.get('x-forwarded-host');
    const xfProto = request.headers.get('x-forwarded-proto');
    const host = xfHost || request.headers.get('host') || request.nextUrl.host;
    const proto = xfProto || request.nextUrl.protocol.replace(':', '') || 'http';
    const origin = `${proto}://${host}`;
    const apiUrl = origin;
    const pkgUrl = `${origin}/api/downloads/glanus-agent-${workspaceId}.pkg`;

    const script = `#!/bin/bash
# Glanus Agent — Automated macOS Installer
# Generated dynamically by the Glanus server
set -e

AGENT_PKG="/tmp/GlanusAgent-$$.pkg"
API_URL="${apiUrl}"
TOKEN="${token}"

echo "============================================"
echo "  Glanus Agent — macOS Installer"
echo "============================================"
echo ""

# Check for root / sudo
if [ "$(id -u)" -ne 0 ]; then
    echo "[ERROR] This script must be run with sudo."
    exit 1
fi

echo "[1/4] Downloading Glanus Agent..."
if command -v curl &>/dev/null; then
    curl -fsSL "${pkgUrl}" -o "\$AGENT_PKG"
else
    echo "[ERROR] curl is required."
    exit 1
fi

echo "[2/4] Installing package..."
installer -pkg "\$AGENT_PKG" -target /

echo "[3/4] Writing agent config..."
CONFIG_DIR="/Library/Application Support/Glanus"
CONFIG_FILE="\$CONFIG_DIR/config.toml"
mkdir -p "\$CONFIG_DIR"

cat > "\$CONFIG_FILE" <<AGENTCFG
# Glanus Agent configuration (auto-generated by install script)
# Do not edit while the service is running.

[agent]
version = "0.1.0"
workspace_id = "${workspaceId}"
pre_auth_token = "\$TOKEN"
registered = false

[server]
api_url = "\$API_URL"
heartbeat_interval = 60

[monitoring]
enabled = true
interval = 10
include_processes = true
max_processes = 5

[updates]
enabled = true
check_interval = 86400
auto_install = false

[inventory]
enabled = true
sync_interval = 21600

[discovery]
enabled = false
scan_interval = 3600

[remote]
enabled = true
AGENTCFG

echo "[4/4] Loading launch daemon..."
if [ -f /Library/LaunchDaemons/com.glanus.agent.plist ]; then
    launchctl load /Library/LaunchDaemons/com.glanus.agent.plist 2>/dev/null || true
    launchctl start com.glanus.agent 2>/dev/null || true
fi

# Cleanup
rm -f "\$AGENT_PKG"

echo ""
echo "============================================"
echo "  Glanus Agent installed successfully!"
echo "  Service: sudo launchctl list | grep glanus"
echo "============================================"
`;

    return new NextResponse(script, {
        status: 200,
        headers: {
            'Content-Type': 'text/x-shellscript; charset=utf-8',
            'Content-Disposition': 'inline; filename="install-glanus.sh"',
            'Cache-Control': 'no-store',
        },
    });
}
